version: "3.8"
services:
  portainer:
    image: portainer/portainer-ce:latest
    restart: always
    container_name: portainer
    ports:
      - "9000:9000"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer:/data
  frontend:
    build:
      context: ./
      dockerfile: Dockerfile
    volumes:
      - ./:/project
    ports:
      - 80:80

volumes:
  portainer:
