name: Dockerfile CI/CD

on:
  push:
    branches: ["prod"]

  workflow_dispatch:

env:
  OS: ubuntu-20.04

jobs:
  # Run tests (TODO).
  tests:
    runs-on: ${{ env.OS }}
    steps:
      - name: Run tests
      - uses: actions/checkout@v2
        run: |
          if [ -f docker-compose.test.yml ]; then
            docker-compose --file docker-compose.test.yml build
            docker-compose --file docker-compose.test.yml run sut
          else
            docker build . --file Dockerfile
          fi

  deploy:
    needs: tests
    runs-on: ubuntu-latest

    permissions:
      contents: read
      packages: write
      id-token: write

    strategy:
      matrix:
          REGISTRY: ['ghcr.io']  # Use docker.io for Docker Hub if empty
          IMAGE_NAME: ${{ github.repository }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install cosign # https://github.com/sigstore/cosign-installer
        if: github.event_name != 'pull_request'
        uses: sigstore/cosign-installer@f3c664df7af409cb4873aa5068053ba9d61a57b6 #v2.6.0
        with:
          cosign-release: "v1.11.0"

      - name: Setup Docker buildx # Workaround: https://github.com/docker/build-push-action/issues/461
        uses: docker/setup-buildx-action@79abd3f86f79a9d68a23c75a09a9a85889262adf

      - name: Log into registry ${{ matrix.REGISTRY }} # https://github.com/docker/login-action
        if: github.event_name != 'pull_request'
        uses: docker/login-action@28218f9b04b4f3f62068d7b6ce6ca5b26e35336c
        with:
          registry: ${{ matrix.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract Docker metadata # https://github.com/docker/metadata-action
        id: meta
        uses: docker/metadata-action@98669ae865ea3cffbcbaa878cf57c20bbf1c6c38
        with:
          images: ${{ matrix.REGISTRY }}/${{ matrix.IMAGE_NAME }}

      - name: Build and push Docker image with Buildx (don't push on PR) # https://github.com/docker/build-push-action
        if: github.event_name != 'pull_request'
        id: build-and-push
        uses: docker/build-push-action@ac9327eae2b366085ac7f6a2d02df8aa8ead720a
        with:
          context: .
          push: ${{ github.event_name != 'pull_request' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          cache-from: type=gha
          cache-to: type=gha,mode=max

      - name: Sign the published Docker image # https://github.com/sigstore/cosign
        if: ${{ github.event_name != 'pull_request' }}
        env:
          COSIGN_EXPERIMENTAL: "true"
        run: echo "${{ steps.meta.outputs.tags }}" | xargs -I {} cosign --force sign {}@${{ steps.build-and-push.outputs.digest }}
