name: Deploy to GitHub Pages

on:
  push:
    branches: ["production"]

  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

# Allow one concurrent deployment
concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run simple preflight build on frontend
        run: docker build ./frontend --file Dockerfile.test

  build:
    needs: tests
    strategy:
      matrix:
        NODE-VERSION: [16]
        PACKAGE-MANAGER: [pnpm]
        PNPM-VERSION: [7]

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: pnpm/action-setup@v2.2.2
        with:
          version: ${{ matrix.PNPM-VERSION }}

      - name: Use Node.js ${{ matrix.NODE-VERSION }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.NODE-VERSION }}
          cache: ${{ matrix.PACKAGE-MANAGER }}

      - name: Restore cache
        uses: actions/cache@v3
        with:
          context: .
          path: ./frontend/.next/cache
          key: ${{ runner.os }}-nextjs-${{ '**/pnpm-lock.yaml' }}-${{ hashFiles('**.[jt]s', '**.[jt]sx') }}
          restore-keys: ${{ runner.os }}-nextjs-${{ '**/pnpm-lock.yaml' }}-

      - name: Install dependencies
        run: ${{ matrix.PACKAGE-MANAGER }} install

      - name: Build with Next.js
        run: ${{ matrix.PACKAGE-MANAGER }} next build

      - name: Static HTML export with Next.js
        run: ${{ matrix.PACKAGE-MANAGER }} next export

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          context: .
          path: ./frontend/out

  deploy:
    needs: build
    runs-on: ubuntu-latest

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v1
