name: Run Simple Preflight Build

on:
  pull_request:
    branches: ["staging"]

  workflow_dispatch:

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Run simple preflight build on frontend
        uses: actions/checkout@v2
        with:
          context: .
          run: docker build ./frontend --file Dockerfile.test